config/routes.rb
Rails.application.routes.draw do

  match '/', to: 'static_pages#homepage', via: [:get, :post]
  match '/create', to: 'static_pages#create', via: [:get, :post]

  root to: 'static_pages#homepage'
end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def homepage
    @contact_request = ContactRequest.new
  end

  def create
    @new_contact_request = ContactRequest.new
    @contact_request = ContactRequest.new(contact_request_params)
    if @contact_request.save
      ContactRequestMailer.receipt(@contact_request[:name], @contact_request[:email]).deliver
      ContactRequestMailer.new_contact_request(@contact_request[:name], @contact_request[:email], @contact_request[:message]).deliver
      flash[:notice] = "Successfully sent your request."
      redirect_to root_path
    else
      flash[:notice] = "Error please try again."
      render root_path
    end
  end

  private

  def contact_request_params
    params.require(:contact_request).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>JOLIE</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper" class="toggled">
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand"><a data-scroll href="#home" class="navbar-link">JOLIE</a></li>
        <li><a data-scroll href="#wholesale" class="navbar-link">Wholesale</a></li>
        <li><a data-scroll href="#about" class="navbar-link">About</a></li>
        <li><a data-scroll href="#contact" class="navbar-link">Contact</a></li>
      </ul>
    </div>

    <div id="page-content-wrapper">
      <div class="container-fluid">
        <button type="button" id="menu-toggle" data-target="#menu-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= yield %>
      </div>
    </div>
  </div>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/static_pages/homepage.html.erb
<div class="row" id="homepage-container">

  <div class="home-container col-md-12" id="home-container">
    <a id="home"> </a>
    <a id="bgndVideo" class="player" data-property="{videoURL:'http://youtu.be/BsekcY04xvQ',containment:'#home-container', autoPlay:true, loop: true, mute:true, startAt: 18, stopAt: 31, opacity:1, ratio: '4/3', showControls: false}"></a>
    <div class="jumbotron">
      <div class="container">
        <h1 id="homepage-header">JOLIE</h1>
        <p id="city">CLOTHING INC.</p>
      </div>
    </div>
  </div>

  <div class="col-md-12" id="wholesale-container">
    <a id="wholesale"> </a>
    <div class="col-md-12" id="wholesale-summary-container">
      <div class="col-md-4" id="wholesale-header-container">
        <h1>Wholesale</h1>
        <h4>Shop for our clothes at FashionGo and LAShowroom.</h4>
      </div>
      <div class="col-md-4" id="wholesale-company1-container">
        <a href="http://www.fashiongo.net/jolie" target="_blank" class="btn wholesale-btn">FashionGo</a>
      </div>
      <div class="col-md-4" id="wholesale-company2-container">
        <a href="http://www.lashowroom.com/jolie" target="_blank" class="btn wholesale-btn">LAShowroom</a>
      </div>
    </div>
  </div>

  <div class="col-md-12" id="about-container">
    <a id="about"> </a>
    <div class="col-md-12" id="about-summary-container">
      <div class="col-md-3" id="about-header-container">
          <h1>About</h1>
      </div>
      <div class="col-md-9" id="about-content-container">
        <h3>
          Since 2003, Jolie Clothing has always been about understated style with attention to detail and fabrication.  We aim to create pieces that make women feel effortless and chic but still put together.  All our manufacturing is done domestically which gives us the advantage of a quick turnaround and quality control. Look for Jolie at your favorite retailers.
        </h3>
      </div>
    </div>
  </div>

  <div class="col-md-12" id="contact-container">
    <a id="contact"> </a>
    <div class="col-sm-6" id="contact-info-container">
      <div class="row contact-row">
        <div class="col-sm-12 contact-info-summary">
          <h1>Contact</h1>
        </div>

        <div class="col-sm-12" id="email-container">
          <%= form_for (@contact_request), url: create_path, html: { class: "form-horizontal" } do |f| %>
            <div class="form-group">
              <%= f.label :name, class: "col-sm-3 control-label" %>
              <div class="col-sm-7">
                <%= f.text_field :name, required: true, class: "form-control" %>
              </div>
            </div>
            <br>
            <div class="form-group">
              <%= f.label :email, class: "col-sm-3 control-label" %>
              <div class="col-sm-7">
                <%= f.text_field :email, required: true, class: "form-control" %>
              </div>
            </div>
            <br>
            <div class="form-group">
              <%= f.label :message, class: "col-sm-3 control-label header green" %>
              <div class="col-sm-7">
                <%= f.text_area :message, class: "form-control", rows: "6" %>
              </div>
            </div>
            <br>
            <div class="col-sm-2 col-sm-offset-5">
              <%= f.submit 'send', class: 'btn btn-default email-submit-btn' %>
            </div>
          <% end %>
        </div>
        <div class="col-sm-12">
          <table class="table">
            <% if flash.any? %>
              <tr>
                <td>
                  <%= flash[:notice] %>
                </td>
              </tr>
            <% end %>
            <tr>
              <td>Address</td>
              <td>Contact Information</td>
            </tr>
            <tr>
              <td>1100 S. San Pedro St. #D-3<br>Los Angeles, CA 90015</td>
              <td>sales@jolieonline.com</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div id="map" class="col-md-6 dark">
    </div>
  </div>
</div>